
package org.lejos.ev3.remote.api.example.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.5
 * Mon May 23 18:43:46 CEST 2016
 * Generated source version: 3.1.5
 */

@XmlRootElement(name = "runEV3RobotMotor", namespace = "http://example.api.remote.ev3.lejos.org/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "runEV3RobotMotor", namespace = "http://example.api.remote.ev3.lejos.org/", propOrder = {"EV3Port", "EV3MotorSpeed", "DegreeOfRotation"})

public class RunEV3RobotMotor {

    @XmlElement(name = "EV3Port")
    private java.lang.String EV3Port;
    @XmlElement(name = "EV3MotorSpeed")
    private int EV3MotorSpeed;
    @XmlElement(name = "DegreeOfRotation")
    private int DegreeOfRotation;

    public java.lang.String getEV3Port() {
        return this.EV3Port;
    }

    public void setEV3Port(java.lang.String newEV3Port)  {
        this.EV3Port = newEV3Port;
    }

    public int getEV3MotorSpeed() {
        return this.EV3MotorSpeed;
    }

    public void setEV3MotorSpeed(int newEV3MotorSpeed)  {
        this.EV3MotorSpeed = newEV3MotorSpeed;
    }

    public int getDegreeOfRotation() {
        return this.DegreeOfRotation;
    }

    public void setDegreeOfRotation(int newDegreeOfRotation)  {
        this.DegreeOfRotation = newDegreeOfRotation;
    }

}

