
package org.lejos.ev3.remote.api.example;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2016-05-23T18:43:47.121+02:00
 * Generated source version: 3.1.5
 * 
 */
 
public class RunEV3Motor_PortTypeServer{

    protected RunEV3Motor_PortTypeServer() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new org.lejos.ev3.remote.api.example.RunEV3Motor();
        String address = "http://localhost:9090/RunEV3MotorPort";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws Exception { 
        new RunEV3Motor_PortTypeServer();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
 
 